const REMOTE="https://raw.githubusercontent.com/sophiamaybea/ideas/engineering-intelligence/engineering-intelligence/dashboard/data/dashboard.json";
let D=null, route=location.hash.slice(1)||"home";
const $=s=>document.querySelector(s), esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
async function load(){try{const r=await fetch(REMOTE+"?v="+Date.now());if(!r.ok)throw 0;D=await r.json()}catch(e){D=await fetch("/data/dashboard.json").then(r=>r.json())}$("#boot").hidden=true;$("#app").hidden=false;$("#footerUpdate").textContent="UPDATED "+new Date(D.meta.lastUpdated).toLocaleString();bind();render()}
function bind(){document.body.addEventListener("click",e=>{const b=e.target.closest("[data-route]");if(b){location.hash=b.dataset.route;route=b.dataset.route;render();$("#rail").classList.remove("open")}const d=e.target.closest("[data-detail]");if(d)openDetail(d.dataset.detail,d.dataset.key)});window.addEventListener("hashchange",()=>{route=location.hash.slice(1)||"home";render()});$(".closeDialog").onclick=()=>$("#detailDialog").close();$("#detailDialog").addEventListener("click",e=>{if(e.target===$("#detailDialog"))$("#detailDialog").close()})}
function shell(title,sub,inner){return `<section class="sectionHead"><h1>${title}</h1><p>${sub}</p></section>${inner}`}
function render(){document.querySelectorAll(".rail button").forEach(b=>b.classList.toggle("active",b.dataset.route===route));({home, repos, prompts, ventures, companies, projects, learning}[route]||home)();scrollTo(0,0)}
function home(){const counts=[["REPOS",D.repos.length],["PROMPTS",D.prompts.length],["VENTURES",D.ventures.length],["COMPANIES",D.companies.length]];$("#view").innerHTML=`
<section class="hero"><div><div class="eyebrow">LIVING ENGINEERING + ECONOMIC INTELLIGENCE</div><h1 class="mega">${D.modes.map(x=>'<span class="slash">/</span>'+esc(x.slice(1))).join(' ')}</h1></div>
<div class="heroActions"><button class="heroLink" data-route="repos">GITHUB GOLD MINE <span>→</span></button><button class="heroLink" data-route="ventures">AUTONOMOUS VENTURES <span>→</span></button><button class="heroLink" data-route="companies">WHO MAKES MONEY <span>→</span></button></div></section>
<div class="statgrid">${counts.map(x=>`<div class="stat"><b>${x[1]}</b><span>${x[0]} INDEXED</span></div>`).join("")}</div>
${shell("WHAT CHANGED","The dashboard opens on deltas, not a wall of information.",`<div class="cards">${D.changes.map(c=>`<article class="card"><span class="tag hot">${esc(c.type)}</span><h2>${esc(c.title)}</h2><p>${esc(c.body)}</p></article>`).join("")}</div>`)}` }
function repos(){let html=shell("REPO RADAR","What the technology actually enables, where we already use it, and whether it should be foundation, component, frontier or rejected.",`<input class="search" id="q" placeholder="SEARCH REPOS / CAPABILITIES"><div class="cards" id="repoCards"></div>`);$("#view").innerHTML=html;const paint=()=>{let q=$("#q").value.toLowerCase();$("#repoCards").innerHTML=D.repos.filter(r=>JSON.stringify(r).toLowerCase().includes(q)).map(r=>`<article class="card clickable" data-detail="repo" data-key="${esc(r.name)}"><span class="tag ${r.status==="PRIORITY"?"hot":""}">${esc(r.status)}</span><span class="tag">${esc(r.licence)}</span><span class="arrow">↗</span><h2>${esc(r.name)}</h2><p>${esc(r.capability)}</p><p><b>USED FOR</b> ${esc(r.usedFor.join(" / "))}</p><p><b>POTENTIAL</b> ${esc(r.potential)}</p></article>`).join("")};$("#q").oninput=paint;paint()}
function prompts(){let html=shell("PROMPT LIBRARY","A working index of the prompt systems we create. New substantial prompts from the preceding hour are added by the hourly intelligence run.",`<input class="search" id="q" placeholder="SEARCH PROMPTS / MODES"><div class="cards" id="promptCards"></div>`);$("#view").innerHTML=html;const paint=()=>{let q=$("#q").value.toLowerCase();$("#promptCards").innerHTML=D.prompts.filter(p=>JSON.stringify(p).toLowerCase().includes(q)).map(p=>`<article class="card clickable" data-detail="prompt" data-key="${esc(p.title)}"><span class="arrow">↗</span>${p.codes.map(x=>`<span class="codepill">${esc(x)}</span>`).join("")}<h2>${esc(p.title)}</h2><p>${esc(p.summary)}</p></article>`).join("")};$("#q").oninput=paint;paint()}
function money(n){return "$"+Number(n).toLocaleString()}
function ventureCard(v){const max=Math.max(...D.ventures.map(x=>x.model.p90));const l=v.model.p10/max*100,w=(v.model.p90-v.model.p10)/max*100,m=v.model.meanRevenue/max*100;return `<article class="card clickable" data-detail="venture" data-key="${esc(v.name)}"><span class="tag hot">WOLFRAM: ${esc(v.status)}</span><span class="arrow">↗</span><h2>${esc(v.name)}</h2><p>${esc(v.thesis)}</p><div class="range"><span class="band" style="left:${l}%;width:${w}%"></span><span class="mean" style="left:${m}%"></span></div><div class="rangeLabels"><span>P10 ${money(v.model.p10)}</span><span>MEAN ${money(v.model.meanRevenue)}</span><span>P90 ${money(v.model.p90)}</span></div><div class="metricline"><div class="metric"><b>${Math.round(v.model.p100*100)}%</b><span>P ≥ $100</span></div><div class="metric"><b>${v.model.medianDaysToFirstDollar}d</b><span>MODELLED FIRST $</span></div><div class="metric"><b>${money(v.model.meanContributionProfit)}</b><span>MEAN CONTRIBUTION</span></div></div></article>`}
function ventures(){ $("#view").innerHTML=shell("VENTURE LAB","Autonomous business ideas generated from our research, each separated into thesis, stack, risk, next falsification test and Wolfram scenario model.",`<div class="notice">${esc(D.meta.modelNotice)}</div><div class="cards">${D.ventures.map(ventureCard).join("")}</div>`)}
function companies(){let html=shell("MONEY MAP","A large financial index first, then qualitative explanation. Initial data is FY2025 net income from SEC-derived filings; profiles are enriched continuously.",`<input class="search" id="q" placeholder="SEARCH 100 PROFITABLE TECH COMPANIES"><div class="list" id="companyList"></div>`);$("#view").innerHTML=html;const paint=()=>{let q=$("#q").value.toLowerCase();$("#companyList").innerHTML=D.companies.filter(c=>JSON.stringify(c).toLowerCase().includes(q)).map(c=>`<div class="row" data-detail="company" data-key="${esc(c.name)}"><span class="rank">#${c.rank}</span><span class="name">${esc(c.name)} <small>${esc(c.ticker)}</small></span><span class="category">${c.profileStatus==="enriched"?"ANALYSED":"QUEUED"}</span><span class="yoy ${c.yoy.startsWith("-")?"down":"up"}">${esc(c.yoy)}</span><span class="profit">${esc(c.netIncome)}</span></div>`).join("")};$("#q").oninput=paint;paint()}
function projects(){$("#view").innerHTML=shell("CURRENT SYSTEMS","Everything already in motion, so the research layer cannot forget what we are actually building.",`<div class="cards">${D.projects.map(p=>`<article class="card"><span class="tag ${p.status==="LIVE"?"hot":""}">${esc(p.status)}</span><span class="tag">${esc(p.kind)}</span><h2>${esc(p.name)}</h2><p>${esc(p.purpose)}</p><p><b>EVIDENCE</b> ${esc(p.evidence)}</p></article>`).join("")}</div>`)}
function learning(){$("#view").innerHTML=shell("LEARNING LOOP","Self-learning is prediction error and measured policy improvement, not an LLM rewriting its own prompt and calling that learning.",`<div class="statgrid"><div class="stat"><b>${money(D.learning.observedRevenue)}</b><span>OBSERVED REVENUE</span></div><div class="stat"><b>${D.learning.observedPaidVentures}</b><span>PAID VENTURES</span></div><div class="stat"><b>${D.learning.predictionErrors.length}</b><span>PREDICTION ERRORS LOGGED</span></div><div class="stat"><b>HOURLY</b><span>EVALUATION CADENCE</span></div></div><div class="loop">${D.learning.loop.map((x,i)=>`<span>${x}</span>${i<D.learning.loop.length-1?'<i>→</i>':''}`).join("")}</div><div class="cards">${D.learning.rules.map((r,i)=>`<article class="card"><span class="tag">RULE 0${i+1}</span><h3>${esc(r)}</h3></article>`).join("")}</div><section class="sectionHead"><h1>WOLFRAM</h1><p>${esc(D.wolfram.method)}</p></section><div class="notice">${esc(D.wolfram.caveat)}</div><div class="cards">${D.wolfram.tests.map(t=>`<article class="card"><span class="tag">TEST</span><h3>${esc(t)}</h3></article>`).join("")}</div>`)}
function openDetail(type,key){let h="";if(type==="repo"){let r=D.repos.find(x=>x.name===key);h=`<span class="tag hot">${esc(r.status)}</span><h2>${esc(r.name)}</h2><h4>CAPABILITY</h4><p>${esc(r.capability)}</p><h4>USED IN OUR SYSTEMS</h4><p>${esc(r.usedFor.join(" / "))}</p><h4>EXAMPLES ALREADY POSSIBLE</h4><p>${esc(r.examples.join(" / "))}</p><h4>POTENTIAL</h4><p>${esc(r.potential)}</p><p><a href="${esc(r.url)}" target="_blank" rel="noreferrer">OPEN REPOSITORY ↗</a></p>`}if(type==="prompt"){let p=D.prompts.find(x=>x.title===key);h=`<span class="tag">PROMPT SYSTEM</span><h2>${esc(p.title)}</h2><p>${esc(p.summary)}</p><h4>MODES</h4><p>${p.codes.map(x=>`<span class="codepill">${esc(x)}</span>`).join("")}</p><p>The library currently stores the durable prompt identity and purpose. The hourly collector will preserve full new prompts as they are created going forward.</p>`}if(type==="venture"){let v=D.ventures.find(x=>x.name===key);h=`<span class="tag hot">MODELLED, NOT EARNED</span><h2>${esc(v.name)}</h2><p>${esc(v.thesis)}</p><h4>AGENT / TECH STACK</h4><p>${esc(v.stack.join(" / "))}</p><h4>WOLFRAM BASELINE</h4><p>Mean monthly revenue: <b>${money(v.model.meanRevenue)}</b><br>10th–90th percentile: <b>${money(v.model.p10)} – ${money(v.model.p90)}</b><br>P(revenue ≥ $100): <b>${Math.round(v.model.p100*100)}%</b><br>Modelled median time to first dollar: <b>${v.model.medianDaysToFirstDollar} days</b></p><h4>MAIN FAILURE MODE</h4><p>${esc(v.risk)}</p><h4>NEXT FALSIFICATION TEST</h4><p>${esc(v.nextTest)}</p>`}if(type==="company"){let c=D.companies.find(x=>x.name===key),p=D.companyProfiles[key];h=`<span class="tag">#${c.rank} FY2025 PROFIT</span><h2>${esc(c.name)}</h2><p><b>${esc(c.netIncome)}</b> net income · ${esc(c.yoy)} YoY</p>${p?`<h4>WHAT IT DOES</h4><p>${esc(p.does)}</p><h4>WHY IT MAKES MONEY</h4><p>${esc(p.why)}</p><h4>MOAT</h4><p>${esc(p.moat)}</p><h4>WHAT WE SHOULD LEARN</h4><p>${esc(p.lesson)}</p>`:`<div class="notice">QUALITATIVE PROFILE QUEUED FOR HOURLY ENRICHMENT. Financial record is already indexed.</div>`}`;}$("#dialogContent").innerHTML=h;$("#detailDialog").showModal()}
load();
setInterval(async()=>{try{const r=await fetch(REMOTE+"?v="+Date.now());if(!r.ok)return;const n=await r.json();if(D&&n.meta.lastUpdated!==D.meta.lastUpdated){D=n;$("#footerUpdate").textContent="UPDATED "+new Date(D.meta.lastUpdated).toLocaleString();render()}}catch(e){}},60000);